---
kind: pipeline
type: docker
name: Build and upstream merge check

steps:
  - name: build
    image: qmkfm/qmk_firmware:latest
    commands:
      - make git-submodule
      - make massdrop/alt:joxcat
  - name: merge upstream
    image: alpine/git:latest
    commands:
      - git remote add master_upstream https://github.com/qmk/qmk_firmware.git
      - git merge master_upstream/master

trigger:
  event:
    - cron
    - push
